package tlt.th.co.toyotaleasing.model.response

import com.google.gson.annotations.SerializedName

data class GetDataTaxResponse(
        @SerializedName("EXT_CONTRACT") var eXTCONTRACT: String? = "",
        @SerializedName("CONTRACT_NO") var cONTRACTNO: String? = "",
        @SerializedName("C_CONTRACT_STATUS") var cCONTRACTSTATUS: String? = "",
        @SerializedName("CUST_NAME") var cUSTNAME: String? = "",
        @SerializedName("C_VEHICLE_MODEL") var cVEHICLEMODEL: String? = "",
        @SerializedName("C_VEHICLE_TYPE") var cVEHICLETYPE: String? = "",
        @SerializedName("C_VEHICLE_GAS") var cVEHICLEGAS: String? = "",
        @SerializedName("C_VEHICLE_AGE") var cVEHICLEAGE: String? = "",
        @SerializedName("C_REG_NO") var cREGNO: String? = "",
        @SerializedName("C_TAX_AMT") var cTAXAMT: String? = "",
        @SerializedName("C_REG_PROVINCE") var cREGPROVINCE: String? = "",
        @SerializedName("C_SERVICE_FEE") var cSERVICEFEE: String? = "",
        @SerializedName("ADDRESS_LINE1") var aDDRESSLINE1: String? = "",
        @SerializedName("ADDRESS_LINE2") var aDDRESSLINE2: String? = "",
        @SerializedName("ADDRESS_LINE3") var aDDRESSLINE3: String? = "",
        @SerializedName("ADDRESS_LINE4") var aDDRESSLINE4: String? = "",
        @SerializedName("PROVINCE_CODE") var pROVINCECODE: String? = "",
        @SerializedName("AMPHUR_CODE") var aMPHURCODE: String? = "",
        @SerializedName("POST_CODE") var pOSTCODE: String? = "",
        @SerializedName("C_COMPULSORY_AMT") var cCOMPULSORYAMT: String? = "",
        @SerializedName("MOBILE_REGIS") var mOBILEREGIS: String? = "",
        @SerializedName("EMAIL_VERI") var eMAILVERI: String? = "",
        @SerializedName("MOBILE_NO") var mOBILENO: String? = "",
        @SerializedName("EMAIL") var eMAIL: String? = "",
        @SerializedName("C_TAX_PENALTY_AMT") var cTAXPENALTYAMT: String? = "",
        @SerializedName("C_TAX_SUM_AMT") var cTAXSUMAMT: String? = "",
        @SerializedName("CURRENT_DATE") var cURRENTDATE: String? = "",
        @SerializedName("C_TAX_EXP_DATE") var cTAXEXPDATE: String? = "",
        @SerializedName("Flag_Pay_ProcessTax") var flagPayProcessTax: String? = "",
        @SerializedName("Flag_GAS") var flagGAS: String? = "",
        @SerializedName("Flag_PORLORBOR") var flagPORLORBOR: String? = "",
        @SerializedName("Flag_TORLORAOR") var flagTORLORAOR: String? = "",
        @SerializedName("FLAG_TAX_OVER3") var flagTaxOver3: String? = "",
        @SerializedName("EMS_NO") var eMSNO: String? = "",
        @SerializedName("FLAG_SETTLEMENT") var flagSETTLEMENT: String? = "",
        @SerializedName("CONTRACT_STATUS_DESC") var contractStatusDesc: String? = "",
        @SerializedName("TAX_DES") var taxDes: String? = "" ,
        @SerializedName("FLAG_TRACKING") var flagTracking: String? = ""
)
