package tlt.th.co.toyotaleasing.analytics

object AnalyticsScreenName {

    //Register Screen name
    const val REGISTER_MAIN = "register_main"
    const val VERIFY_EMAIL_SUCCESS = "verify_email_success"
    const val VERIFY_EMAIL_FAIL = "verify_email_fail"
    const val REGISTER_TERMS_CONDITIONS = "register_terms&conditions"
    const val REGISTER_PRIVACY_POLICY = "register_privacypolicy"
    const val REGISTER_CUSTOMER_INFO = "register_customerinfor"
    const val REGISTER_CUSTOMER_INFO_ERROR = "register_customerinfor_error"
    const val REGISTER_SELECT_PHONE = "register_selectphone"
    const val REGISTER_SELECT_PHONE_CALL = "register_selectphone_call"
    const val REGISTER_FILL_OTP = "register_fillotp"
    const val REGISTER_FILL_OTP_ERROR = "register_fillotp_error"
    const val REGISTER_FILL_OTP_TIMEOUT = "register_fillotp_timeout"
    const val REGISTER_SUCCESS = "register_success"
    const val REGISTER_SET_PIN = "register_setpin"
    const val REGISTER_SET_PIN_SUCCESS = "register_setpin_success"
    const val REGISTER_SET_TOUCH_ID = "register_settouchid"
    const val LOGIN_TOUCH_ID = "login_touchid"
    const val LOGIN_TOUCH_ID_FAIL = "login_touchid_fail"
    const val GUIDE = "Guide"
    const val TUTORIAL_PAGE_1 = "Tutorial_page1"
    const val TUTORIAL_PAGE_2 = "Tutorial_page2"
    const val TUTORIAL_PAGE_3 = "Tutorial_page3"
    const val LOGIN_PINCODE = "login_pincode"
    const val LOGIN_PINCODE_FAIL = "login_pincode_fail"
    const val MAIN_MENU = "Mainmenu"
    const val MAIN_MENU_NON_CUS = "Mainmenu_noncus"
    const val PUSH_POPUP = "push_popup"

    //Installment
    const val INSTALLMENT_MY_CAR = "installment_mycar"
    const val INSTALLMENT_MY_CAR_SELECT_CAR = "installment_mycar_selectcar"
    const val INSTALLMENT_MY_CONTRACT = "installment_mycontract"
    const val INSTALLMENT_MY_CONTRACT_POPUP = "installment_mycontract_popup"
    const val INSTALLMENT_PAYOFF = "installment_payoff"
    const val INSTALLMENT_PAYOFF_INTEREST = "installment_payoff_interest"
    const val INSTALLMENT_REFINANCE = "installment_refinance"
    const val INSTALLMENT_REFINANCE_INTEREST = "installment_refinance_interest"
    const val INSTALLMENT_MY_CONTRACT_CHANGE_ADDRESS = "installment_mycontact_changeaddress"
    const val INSTALLMENT_MY_CONTRACT_CHANGE_ADDRESS_CONFIRM = "installment_mycontact_changeaddress_confirm"
    const val INSTALLMENT_MY_CONTRACT_CHANGE_EMAIL = "installment_mycontact_changeemail"
    const val INSTALLMENT_DETAIL = "installment_detail"
    const val INSTALLMENT_PAYMENT_LIST = "installment_paymentlist"
    const val INSTALLMENT_ADJUST_PAYMENT = "installment_adjust_payment"
    const val INSTALLMENT_ADD_OTHER = "installment_add_other"
    const val PAYMENT_CHANNEL = "payment_channel"
    const val PAYMENT_SUCCESS = "payment_success"
    const val PAYMENT_FAIL = "payment_fail"
    const val PAYMENT_HISTORY = "payment_history"
    const val PAYMENT_HISTORY_SELECT_CAR = "payment_history_selectcar"
    const val PAYMENT_HISTORY_FILTER = "payment_history_filter"
    const val NOTIFICATION = "notification"
    const val NOTIFICATION_FILTER = "notification_filter"
    const val NOTIFICATION_SELECT_CAR = "notification_selectcar"

    //ETC & Setting
    const val NEWS_AND_PROMOTION_LIST = "news&promotion_list"
    const val NEWS_AND_PROMOTION_DETAIL = "news&promotion_detail"
    const val NEWS_AND_PROMOTION_OIL = "news&promotion_oil"
    const val NEWS_AND_PROMOTION_TRAFFIC = "news&promotion_traffic"
    const val CONTACT_MAIN = "contact_main"
    const val CONTACT_QUESTION = "contact_question"
    const val MAP_OFFICE = "map_office"
    const val MAP_LOCATIONSETTING = "map_locationsetting"
    const val MAP_DEALER = "map_dealer"
    const val MAP_DEALER_DETAIL = "map_dealer_detail"
    const val MAP_DEALER_SEARCH = "map_dealer_search"
    const val MAP_DEALER_NO_SEARCH = "map_dealer_no_search"
    const val DOWNLOAD_DOC = "download_doc"
    const val FAQ_TOPIC = "faq_topic"
    const val FAQ_QUESTION = "faq_question"
    const val SETTING_MAIN = "setting_main"
    const val SETTING_CHANGE_EMAIL = "setting_change_email"
    const val SETTING_CHANGE_EMAIL_SUCCESS = "setting_change_email_success"
    const val SETTING_CAR_PROFILE = "setting_carprofile"

    //Tax
    const val TAX_MAIN = "tax_main"
    const val TAX_UPDATE_YEAR = "tax_update_year"
    const val TAX_LABEL_DELIVERY_STATUS = "taxlabel_delivery_status"
    const val OWNERSHIP_TRANSFER_TRACKING = "ownership_transfer_tracking"
    const val E_COMMERECE = "e_commerce"
    const val TAX_LABEL_RECEIVE_ADDRESS = "taxlabel_receive_address"
    const val TAX_LABEL_RECEIVE_EMAIL = "taxlabel_receive_email"
    const val TAX_PAYMENT_LIST = "tax_paymentlist"
    const val TAX_COM_INSURANCE_UPLOAD = "tax_cominsurance_upload"
    const val TAX_INSPECTIONCER_UPLOAD = "tax_inspectioncer_upload"
    const val TAX_COMINSURANCE_SELECTPOPUP = "tax_cominsurance_selectpopup"
    const val TAX_NGVCER_SENT = "tax_ngvcer_sent"

    //Insurance
    const val INSURANCE_MAIN = "tib_main"
    const val INSURANCE_INFOR = "tib_current_insurance"
    const val INSURANCE_POLICY_STATUS = "insurance_policystatus"
    const val INSURANCE_QUOTATION_FROM_TYPE = "insurance_quotationform_type"
    const val INSURANCE_RECOMMENDED = "insurance_recommended"
    const val INSURANCE_PAYMENT_DETAIL = "insurance_payment_detail"
    const val INSURANCE_CONTACT = "insurance_contact"
    const val INSURANCE_CONTACT_EMERGENCY_CALL = "insurance_contact_emercall"
    const val INSURANCE_CONTACT_CLAIM = "insurance_contact_claim"
    const val INSURANCE_CONTACT_QUESTION = "insurance_contact_question"
    const val INSURANCE_TIB_CLUB = "insurance_tibclub"
    const val INSURANCE_TIB_CLUB_ACTIVITY = "insurance_tibclub_activity"

    const val TIB_CONTACT_US = "tib_contact_us"
    const val TIB_EMERGENCY_CALL = "tib_emergency_call"
    const val TIB_INSURANCE_INFOR = "tib_insurance_infor"
    const val TIB_INSURANCE_HISTORY = "tib_insurance_history"
    const val TIB_CLAIM_CENTER = "tib_claim_center"
    const val TIB_CALL = "tib_call"
    const val TIB_INSURACE_POLICY = "tib_insurace_policy"
    const val TIB_MAIN = "tib_main"
    const val TIB_OTHER = "tib_other"


    const val ONLINE_APP = "online_app"
    const val ONLINE_MAIN_CAR = "online_main_car"
    const val ONLINE_CAR_ADD   =  "online_car_add"
    const val ONLINE_CAR_DELETE  = "online_car_delete"
    const val ONLINE_CAR_CLICK  = "online_car_click"
    const val ONLINE_IDCARD  = "online_idcard"
    const val ONLINE_IDCARD_ADD  = "online_idcard_add"
    const val ONLINE_LIVENESS  = "online_liveness"
    const val ONLINE_LIVENESS_ADD  = "online_liveness_add"
    const val ONLINE_INFORMATION  = "online_information"
    const val ONLINE_DOPA  = "online_dopa"
    const val ONLINE_DOPA_SUCCESS  = "online_dopa_success"
    const val ONLINE_DOPA_UNSUCCESS  = "online_dopa_unsuccess"
    const val ONLINE_ADDDOC  = "online_adddoc"
    const val ONLINE_ADDDOC_SUBMIT  = "online_adddoc_submit"
    const val ONLINE_PERSONAL  = "online_personal"
    const val ONLINE_PERSONAL_MAP_CLICK  = "online_personal_map_click"
    const val ONLINE_CDD  = "online_cdd"
    const val ONLINE_NDID_TERMCON  = "online_ndid_termcon"
    const val ONLINE_NDID_TERMCON_ACCEPT  = "online_ndid_termcon_accept"
    const val ONLINE_NDID_TERMCON_UNACCEPT  = "online_ndid_termcon_unaccept"
    const val ONLINE_E_CONSENT  = "online_e_consent"
    const val ONLINE_E_CONSENT_ACCEPT  = "online_e_consent_accept"
    const val ONLINE_E_CONSENT_UNACCEPT  = "online_e_consent_unaccept"
    const val ONLINE_WAIT_NDID  = "online_wait_ndid"
    const val ONLINE_BANK_NDID  = "online_bank_ndid"
    const val ONLINE_BANK_NDID_CLICK  = "online_bank_ndid_click_"
    const val ONLINE_CREDIT_CONSIDER  = "online_credit_consider"
    const val ONLINE_CREDIT_RESULT  = "online_credit_result"
    const val ONLINE_CREDIT_RESULT_ACCEPT  = "online_credit_result_accept"
    const val ONLINE_CREDIT_RESULT_UNACCEPT  = "online_credit_result_unaccept"
    const val ONLINE_CREDIT_DOFFER_ACCEPT  = "online_credit_doffer_accept"
    const val ONLINE_CREDIT_DOFFER_UNACCEPT  = "online_credit_ doffer _unaccept"
    const val ONLINE_CREDIT_ADDDOC_SUBMIT  = "online_credit_adddoc_submit"
    const val ONLINE_VERIFY_CONFIRM  = "online_verify_confirm"
    const val ONLINE_VERIFY_CONFIRM_MAP_CLICK  = "online_verify_confirm_map_click"
    const val ONLINE_DEALER  = "online_dealer"
    const val ONLINE_DEALER_MAP_ADD  = "online_dealer_map_add"
    const val ONLINE_SUMMMARY  = "online_summmary"
    const val ONLINE_SUMMARY_DEALER_CHANGE  = "online_summary_dealer_change"
    const val ONLINE_SUMMARY_SCANQR  = "online_summary_scanqr"
    const val ONLINE_SUMMARY_VIEW_OTHER_EXPENSE  = "online_summary_view_other_expense"
    const val ONLINE_ENDGAME  = "online_endgame"
    const val ONLINE_ENDGAME_VIEW_CONTRACT  = "online_endgame_view_contract"
    const val ONLINE_ENDGAME_VIEW_INSTALMENT  = "online_endgame_view_instalment"
    const val ONLINE_MAP  = "online_map"
    const val ONLINE_MAP_ADD  = "online_map_add"
    const val ONLINE_STREET_VIEW  = "online_street_view"
    const val ONLINE_STREET_VIEW_ADD  = "online_street_view_add"

}